"""
Contract for all Financial Effect creation strategies.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

from income_analytics.domain.effects.financial_effect import FinancialEffect
from income_analytics.domain.entities.financial_event import FinancialEvent


class FinancialEffectStrategy(ABC):
    """
    Defines how a Financial Event is translated into Financial Effects.

    Concrete strategies encapsulate the business rules for each
    FinancialEventType.
    """

    @abstractmethod
    def create(
        self,
        event: FinancialEvent,
    ) -> tuple[FinancialEffect, ...]:
        """
        Creates the Financial Effects generated by a Financial Event.
        """
